### ISSUE TITLE
netstat -i output

### ISSUE THREAD

**Issue by gunhu** [ecki/net-tools#10]
Hi everyone,

I wanted to point out something on `netstat -i` output:

>$ netstat -i
Kernel Interface table
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
lo       65536        2      0      0 0             2      0      0      0 LRU
>

When I'm debugging network issues I want to have all information about a network card.

I mean all relevant timers to see if something wrong is going on.

I don't see any RX-FRAME or TX-FRAME field, I need to add `-e` option.

Can I make a PR to have an output like this:

>$ netstat -i
Kernel Interface table
Iface      MTU    RX-OK RX-ERR RX-DRP RX-FRAME RX-OVR    TX-OK TX-ERR TX-DRP TX-FRAME TX-OVR Flg
lo       65536        2      0     0 0 0             2      0      0      0 0 LRU
>

Thanks for your kind advice about it.

Regards,

**Comment by ecki** [comment]
Hello Alexis,

Thanks for the report. I think the columns selected are designed to fit into 80 colums. So if we want to add more we should I guess either have a new Option or make it sensitive to terminal width (and Show all coluimns for pipes).

This would also reduce compliations with scripts parsing the Output (which is most likely not a good idea…)

So what do you think, new option or detecting terminal width?

Gruss
Bernd
-- 
http://bernd.eckenfels.net

Von: Alexis VACHETTE
Gesendet: Donnerstag, 29. November 2018 17:52
An: ecki/net-tools
Cc: Subscribed
Betreff: [ecki/net-tools] netstat -i output (#10)

Hi everyone,
I wanted to point out something on netstat -i output:
$ netstat -i
Kernel Interface table
Iface MTU RX-OK RX-ERR RX-DRP RX-OVR TX-OK TX-ERR TX-DRP TX-OVR Flg
lo 65536 2 0 0 0 2 0 0 0 LRU
I don't see any RX-FRAME or TX-FRAME field, I need to add -e option.
Can I make a PR to have an output like this:
$ netstat -i
Kernel Interface table
Iface MTU RX-OK RX-ERR RX-DRP RX-FRAME RX-OVR TX-OK TX-ERR TX-DRP TX-FRAME TX-OVR Flg
lo 65536 2 0 0 0 0 2 0 0 0 0 LRU
Thanks for your kind advice about it.
Regards,

**Comment by gunhu** [comment]
I came with a new idea.

Add CRC / Frame errors to RX or TX counters.

No breaking change in the output.

Regards,

**Comment by ecki** [comment]
Thanks, adding the numbers actually looks like a good compromise. Will have to make sure to document that in manpage and release notes.

**Comment by ecki** [comment]
It would be great if you could. Can you also squash your commits, so its a single one with the sum (of the right fields) and the man adoption.

**Comment by gunhu** [comment]
Hi Bernd,

I added manpage details on my PR.

I'm only French native speaker and I can write/speak English too.

Feel free to review German and Portuguese part if it's not correct.

Regards,

**Comment by ecki** [comment]
Marged here: https://github.com/ecki/net-tools/commit/6cd51595e0b6d1fd679f77b0d8c3d7c5bc6f91a8
