### ISSUE TITLE
netstat - host processes not visible using -p option inside docker

### ISSUE THREAD

**Issue by prashanthjbabu** [ecki/net-tools#12]
When running a docker in privileged and host network mode, netstat is not able to populate the PIDs/Process Names of the host. 
Example:
**prash@prash-laptop:~/ $ docker run --privileged=true --net=host  -ti alpine sh
/ # apk add net-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/2) Installing mii-tool (1.60_git20140218-r2)
(2/2) Installing net-tools (1.60_git20140218-r2)
Executing busybox-1.28.4-r1.trigger
OK: 5 MiB in 15 packages
/ # netstat -apnt
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -                   
tcp        0      0 192.168.1.88:53454      216.58.197.37:443       ESTABLISHED -                   
tcp        0      0 192.168.1.88:44128      74.125.200.188:5228     ESTABLISHED -**                   

Since docker has the option to run in network host mode , the flows of the host are visible. Although the process names and PIDs are not getting populated.This is because /proc of the docker does not match the host. Hence netstat is not able to get process information.
Now a days a lot of linux tools try to be container(lxc/docker) compliant . A common approach for many tools is to mount the procfs of the host inside the docker like /hostfs/proc and then pass this PATH to the linux tool as an argument/env variable etc (Ref : https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md)
It would be great if netstat too supports this feature so that any monitoring application which runs inside a container can be used to monitor host traffic/processes etc.

**Comment by nikhilo** [comment]
I think you also need `--pid=host` along with `--net=host` and `--privileged=true` for getting the PID/process names.

**Comment by prashanthjbabu** [comment]
@nikhilo I tried it and it worked . Thanks for helping out :)
