### ISSUE TITLE
netstat: command not found - Alpine Linux

### ISSUE THREAD

**Issue by MekayelAnik** [ecki/net-tools#25]
I am building an alpine based docker image, in which I have installed "net-tools" using <code>apk add --no-cache --update net-tools</code>
But when I run the docker image the output in the console is <code>netstat: command not found</code>
Oddly enough when I install anything (any apk i.e. nano, htop etc.) the "netstat" begins to produce output.
For example, After deploying the container, if I run: <code>apk add --no-cache --update htop</code>
The <code>netstat</code> starts working. Until this, the output was <code>netstat: command not found</code>
I have found the REASON for this issue is, the "netstat" is not present <code>/bin</code> directory until another program is installed!
As soon as another program gets installed, the "netstat" somehow appears in the <code>/bin</code> directory!
This is very strange!
Why wouldn't "netstat" be present in the <code>/bin</code> directory until another program is installed?
I am using  <q>alpine:latest</q> as base image.
Can anyone look into this? Many thanks in advance.

**Comment by ecki** [comment]
That sounds like a alpine problem, not much net-stat can do. But if you tell me the docker command to create a replicator and paste the exact error message maybe someone can have a look. It sounds a bit like the alpine package is missing a dependency declaration. Maybe some libc variants?

**Comment by MekayelAnik** [comment]
There was a problem in the borrowed Dockerfile, which caused the above issue.
Thanks for your reply and time.
net-tools is a great and important package. Keep up the great work.
Regards.
