### ISSUE TITLE
[netstat]Question: Code pathes of cached kernel route table (IPv6)

### ISSUE THREAD

**Issue by ChriMarMe** [ecki/net-tools#34]
So given the command `netstat -r6C` executes the function [rprint_cache6](https://github.com/ecki/net-tools/blob/20a78e06a69bd9b6b4e15468201d5d3aa9c395db/lib/inet6_gr.c#L157) which tries to open the file
`/proc/net/ndisc`. This file does not exist on my machine, nor on machines of some friends. Under which circumstances does this file exist? I can't find any information about it in the linux kernel, so I wonder about this code path.

Can someone provide some information about that? Is that legacy compatibility? Code does not provide enough information or documentation to understand.

**Comment by ecki** [comment]
Yes all of net-Tools is legacy :)

but more seriously don’t know when Linux kernel removed it.

**Comment by ChriMarMe** [comment]
First of all: Thank you, again, for clarification. 
I already suspected something like this but needed confirmation. 

IPv4 route cache used file `/proc/net/rt_cache`, while IPv6 got it in `/proc/net/ndisc`. The first exists but is empty, the latter was removed from kernel capabilities somewhen so it seems.

**Comment by ecki** [comment]
Thanks for the research, i think I will just remove it completely. If somebody has an older kernel and needs it, they can use older releases. That's much easier than describing what it was when it was removed and how to deal with v4/v6 differences. I don't think productive scripts (besides monitoring) would break/miss it

**Comment by ChriMarMe** [comment]
I did some digging and came across this information:

>iptables2 code gives hints about route cache being removed.
>
>Also the manpage of iptables2-package/ip-route subcommand (the ip command) gives a hint to that:
>[ip-route.8 man-page](https://github.com/iproute2/iproute2/blob/39e4b6f5f315680ac914187b1d5526c005b8c0d8/man/>man8/ip-route.8.in#L1356C10-L1357C75)
```
.SH NOTES
Starting with Linux kernel version 3.6, there is no routing cache for IPv4
anymore. Hence
.B "ip route show cached"
will never print any entries on systems with this or newer kernel versions.
```

For IPv6 I found [this](https://vincent.bernat.ch/en/blog/2017-ipv6-route-lookup-linux) source which states, that route cache is still in the kernel but only creates a cache entry if a PMTU (Path MTU Discovery) exception happens. 

> Starting from Linux 4.2 [commit 45e4fd26683c](https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=45e4fd26683c9a5f88600d91b08a484f7f09226a), only a PMTU exception would create a cache entry. 
> A router doesn’t have to handle these exceptions, so only hosts would get cache entries.

> And they should be pretty rare. Martin KaFai Lau, from Facebook, [explains](https://www.spinics.net/lists/netdev/msg330403.html):
> Out of all IPv6 RTF_CACHE routes that are created, the percentage that has a different MTU is very small. 
> In one of our end-user facing proxy server, only 1k out of 80k RTF_CACHE routes have a smaller MTU. 
> For our DC traffic, there is no MTU exception.
